export { default as PHome } from './PHome'
export { default as PHall } from './PHall'
export { default as PAdd } from './PAdd'
export { default as PGame } from './PGame'
export { default as PPastGames } from './PPastGames'
export { default as PPastGame } from './PPastGame'
export { default as PHistoryGame } from './PHistoryGame'
